# fly.toml app configuration file generated for tipbot-twilight-star-4707 on 2024-04-03T15:49:09+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tipbot-twilight-star-4707'
primary_region = 'lax'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 100

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
